---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cluster-gke-beta
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: url
      value: https://github.com/devsecfranklin/cluster-gke-beta
